version: "3"
name: "accounting"
services:
  db:
    image: postgres
    env_file: ./backend/.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=accounting-db
    restart: always
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    environment:
      - DB_HOST=db
    ports:
      - "8000:8000"
    volumes:
      - .:/src
    depends_on:
      - db
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: on-failure
